### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [netSolver18752/prj-rev-bwfs-dasmoto#2]
https://github.com/netSolver18752/prj-rev-bwfs-dasmoto/blob/master/Dasomoto/index.html#L6

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found [here](https://www.w3schools.com/html/html_entities.asp)

**Comment by netSolver18752** [comment]
Thanks for the tip.
