### ISSUE TITLE
IMPORTANT - syntax errors

### ISSUE THREAD

**Issue by franfranfranfran** [netSolver18752/prj-rev-bwfs-dasmoto#4]
woops, keep an eye out for errors in the syntax of your code. here's a couple examples i found - 

https://github.com/netSolver18752/prj-rev-bwfs-dasmoto/blob/master/Dasomoto/index.html#L15
no need for the semi-colon after the class attribute. 

https://github.com/netSolver18752/prj-rev-bwfs-dasmoto/blob/master/Dasomoto/index.html#L11
h3 tag used to open, h2 used to close

remember that h1 is the largest heading element so it would likely be used as the main heading on the page. header is meant to be used much like a div element
heres some more info on heading elements - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
and header - https://developer.mozilla.org/nl/docs/Web/HTML/Element/header
not necessarily a syntax error but more appropriate elements could likely be chosen

**Comment by netSolver18752** [comment]
That's strange. Don't know how I made those mistakes. I know the proper syntax for the heading elements. Will review code more thoroughly. Thanks.
