### ISSUE TITLE
IMPORTANT - local resources

### ISSUE THREAD

**Issue by franfranfranfran** [netSolver18752/prj-rev-bwfs-dasmoto#5]
https://github.com/netSolver18752/prj-rev-bwfs-dasmoto/blob/master/Dasomoto/index.html#L16
https://github.com/netSolver18752/prj-rev-bwfs-dasmoto/blob/master/Dasomoto/resources/css/style.css#L5
etc...

it is very important for your resources to be included in your project. links to outside sources can easily become broken if that source decides to change where they are stored or take them down. save your images locally to an 'images' folder inside of resources and then link to them using relative file paths.
more info about relative file paths can be found [here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/)

**Comment by netSolver18752** [comment]
Thanks.
