### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [netSolver18752/prj-rev-bwfs-dasmoto#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good start on this project. The site looks great and you did an excellent job keeping the project folder organized using a separate resources folder. Nice work using classes to help label content throughout as well.

Behind the scenes, it is very important to keep your code as neat and readable as possible. Use indentation to help represent the nested relationships between sections and elements to make your code easier to read at a glance. Also, make sure to include your resources with your project folder and then use relative file paths to link to them throughout. This will ensure that you always know exactly where these items are stored.

As a next step, try using divs and to reinforce the content structure of the page. Sectioning off each content block will help with styling, readability, and creating a well-defined structure for the page. All of these things become more and more crucial as your projects grow in size and complexity.

Have fun and keep up the good work!

**Comment by netSolver18752** [comment]
Thank you for the feedback.
